name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
      - run: dart pub global activate jaspr_cli
      - run: jaspr build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
      - run: flutter pub get
      - run: flutter test
